# --- Database Connection ---
db.auth.url=jdbc:mysql://localhost:3306/university_auth
db.erp.url=jdbc:mysql://localhost:3306/university_erp
db.username=root
db.password=6789

# --- Seed Users ---
seed.admin.username=admin1
seed.admin.password=password123
seed.instructor.username=inst1
seed.instructor.password=password123
seed.student.username=stu1
seed.student.password=password123